yuncms:
  build: ./
  volumes:
    - ./:/var/www
  links:
    - mysql
    - xunsearch
  ports:
    - 80:80

mysql:
  image: mysql:latest
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD:123456
  ports:
    - 3306:3306

xunsearch:
  image: hightman/xunsearch:latest
  volumes:
    - ./xunsearch:/usr/local/xunsearch/data
  ports:
    - 8383:8383
    - 8384:8384
